services:
  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_URL=/api
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/portfolio
      - JWT_SECRET=${JWT_SECRET:-cf=sSSvHH1&=QBsdLA_%|q77v8j7v.}
    depends_on:
      - mongo
    volumes:
      - ./backend/storage/uploads:/app/storage/uploads
    restart: unless-stopped

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
